server:
    port: 8080
spring:
    application:
        name: backend
    datasource:
        url: jdbc:mysql://localhost:3306/zoile
        username: root
        password: z1z2z3z4
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.MySQL8Dialect
        # jackson:
        #     serialization:
        #         write-dates-as-timestamp: false    